<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = User::first();
        $categories = Category::all();

        if (!$admin || $categories->isEmpty()) return;

        for ($i = 1; $i <= 5; $i++) {
            $title = "Sample Article Title $i";
            Article::create([
                'author_id' => $admin->id,
                'category_id' => $categories->random()->id,
                'title' => $title,
                'slug' => Str::slug($title),
                'excerpt' => "This is a short excerpt for sample article $i. It contains some basic summary of the content.",
                'content' => "<h2>Content for Article $i</h2><p>This is the main body content for article $i. It was generated by the seeder to test the layout and SEO features.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>",
                'status' => 'published',
                'published_at' => now(),
                'seo_title' => $title . " | Admin Dashboard",
                'seo_description' => "Meta description for sample article $i to test SEO functionality.",
                'seo_focus_keyword' => "Sample Article",
            ]);
        }
    }
}
